config/routes.rb
Appointment::Application.routes.draw do


  get "pages/about"

  resources :channels
  resources :broadcasts
  resource :today, :controller => :today, :only => :show


  resources :users, :only => [:show], :shallow => true do
    resources :following, :only => [:index, :create, :destroy], :controller => :followings
  end
#  resources :followings, :only => [:create, :destroy]
  resources :intentions, :only => [:new, :create, :destroy, :watchers]
  resource :settings, :only => [:show]

  #resources :on, :constraints => {:id => /[0-9][0-9][0-9][0-9]\/[0-9][0-9]\/[0-9][0-9]/}, :as => :day, :controller => :days, :only => :show

  match ':year/:month/:day', :to => 'days#show', :year => /[0-9][0-9][0-9][0-9]/, :month => /[0-9][0-9]/, :day => /[0-9][0-9]/

  match 'logout', :to => 'sessions#destroy'
  match 'watchers', :to => 'intentions#watchers'
  match 'processing', :to => 'pages#processing'
  match '/auth/:provider/callback', :to => 'sessions#create'
  match '/auth/failure', :to => 'pages#index'

  root :to => "homepage#show"

end

app/models/channel.rb
class Channel < ActiveRecord::Base

  validates_presence_of :name

  has_many :broadcasts, :dependent => :destroy

end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController

  before_filter :authenticate_admin!
  before_filter :find_channel, :only => [:show, :edit, :update, :destroy]

  def index
    @channels = Channel.all
  end

  def new
    @channel = Channel.new
  end

  def create
    @channel = Channel.new(params[:channel])

    if @channel.save
      redirect_to channel_path(@channel)
    else
      render :new
    end
  end

  def update

    if @channel.update_attributes(params[:channel])
      redirect_to channel_path(@channel)
    else
      render :edit
    end

  end

  def destroy
    @channel.destroy

    redirect_to channels_path
  end

  protected

    def find_channel
      @channel = Channel.find(params[:id])
    end


end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/views/channels/_fields.html.erb
<p>
  <%= f.label :name %>
  <%= f.text_field :name %>
</p>

<p>
  <%= f.label :xml_url, "XML URL (if available)" %>
  <%= f.text_field :xml_url %>
</p>

app/views/channels/edit.html.erb
<h1>Edit <%= @channel.name %></h1>

<% form_for @channel do |f| %>

  <%= render :partial => "fields", :locals => {:f => f} %>

  <%= f.submit "Save" %>

<% end %>

app/views/channels/index.html.erb
<h1>Channels</h1>

<ul>
  <% @channels.each do |channel| %>
    <li><%= link_to channel.name, channel %></li>
  <% end %>
</ul>

app/views/channels/new.html.erb
<h1>Add a Channel</h1>

<%= form_for @channel do |f| %>

  <%= render :partial => "fields", :locals => {:f => f} %>

  <%= f.submit "Add" %>

<% end %>

app/views/channels/show.html.erb
<h1><%= @channel.name %></h1>

<%= link_to "Edit", edit_channel_path(@channel) %>

<%= button_to "Delete", channel_path(@channel), {:method => :delete} %>