config/routes.rb
Appointment::Application.routes.draw do


  get "pages/about"

  resources :channels
  resources :broadcasts
  resource :today, :controller => :today, :only => :show


  resources :users, :only => [:show], :shallow => true do
    resources :following, :only => [:index, :create, :destroy], :controller => :followings
  end
#  resources :followings, :only => [:create, :destroy]
  resources :intentions, :only => [:new, :create, :destroy, :watchers]
  resource :settings, :only => [:show]

  #resources :on, :constraints => {:id => /[0-9][0-9][0-9][0-9]\/[0-9][0-9]\/[0-9][0-9]/}, :as => :day, :controller => :days, :only => :show

  match ':year/:month/:day', :to => 'days#show', :year => /[0-9][0-9][0-9][0-9]/, :month => /[0-9][0-9]/, :day => /[0-9][0-9]/

  match 'logout', :to => 'sessions#destroy'
  match 'watchers', :to => 'intentions#watchers'
  match 'processing', :to => 'pages#processing'
  match '/auth/:provider/callback', :to => 'sessions#create'
  match '/auth/failure', :to => 'pages#index'

  root :to => "homepage#show"

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :authorizations, :dependent => :destroy
  has_many :intentions, :dependent => :destroy
  has_many :friendships, :dependent => :destroy
  has_many :friends, :through => :friendships
  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id", :dependent => :destroy
  has_many :inverse_friends, :through => :inverse_friendships, :source => :user

  validates_presence_of :username
  validates_uniqueness_of :username

  accepts_nested_attributes_for :authorizations

  attr_readonly :username
  attr_protected :admin

  def following?(user)
    self.friendships.find_by_friend_id(user.id)
  end

  def recent_intentions
    intentions.joins(:broadcast).includes(:broadcast => :channel).order("broadcasts.start DESC").limit(10)
  end

  def friends_with_intentions
    friends.where("intentions_count > 0")
  end

  def self.create_from_hash!(hash)
    create(:name => hash['user_info']['name'], :username => hash['user_info']['nickname'])
  end

  def retrieve_twitter_friends

    Twitter.configure do |config|
      config.consumer_key = CONSUMER_KEY
      config.consumer_secret = CONSUMER_SECRET
      config.oauth_token = self.twitter.oauth_token
      config.oauth_token_secret = self.twitter.oauth_secret
    end

    friend_ids = []

    begin
      cursor = -1
      while (cursor != 0) do
        twitter_friends = Twitter.friends({:cursor => cursor})
        cursor = twitter_friends.next_cursor
        twitter_friends.users.each do |friend|
          friend_ids << friend.id
        end
      end
    end

    puts friend_ids
#        auth = { 'uid' => friend['id'], 'provider' => 'twitter',
#                 'user_info' => { 'nickname' => friend['screen_name'], 'image' => friend['profile_image_url'], 'name' => friend['name']},
 #                'credentials' => { 'token' => '', 'secret' => ''}}
        #if @auth = Authorization.find_from_hash(auth)
        #  @auth.update_from_hash(auth)
        #else
        #  @auth = Authorization.create_from_hash(auth)
        #end
        #self.friends << @auth.user unless Friendship.find(:first, :conditions => {:friend_id => @auth.user.id, :user_id => self.id})
#      end
#    end
#    rescue Twitter::RateLimitExceeded
#      return false
#    end
#    true
  end

  def twitter
    self.authorizations.find(:first, :conditions => { :provider => 'twitter' })
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find_by_username!(params[:id])
  end

  def update
    @user = User.find_by_username!(params[:id])
    raise "Not Authorized" unless @user == current_user

    if @user.update_attributes(params[:user])
      redirect_to root_path
    else
      render "settings/show"
    end

  end


  def create
    @user = User.new(params[:user])

    if @user.save
      self.current_user = @user
      redirect_to root_path
    else
      render :new
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper

  def username_path(user, options = {})
    url_for(options.merge(:controller => :users, :action => :show, :id => user.username))
  end

  def username_url(user, options = {})
    username_path(user, options.merge!(:only_path => false))
  end


end

app/views/users/new.html.erb
<h1>Complete your registration</h1>

<%= form_for @user do |f| %>

<p>
  <%= f.label :username, "username" %>
  <%= f.text_field :username %>
  (note: you can't change this later)
</p>

<p>
  <%= f.label :name, "Full name" %>
  <%= f.text_field :name %>
</p>

<p>
  <%= f.label :email, "e-mail address" %>
  <%= f.text_field :email %>
  (we won't spam you, promise.)
</p>

  <%= f.fields_for :authorizations do |a| %>
    <%= a.hidden_field :oauth_token %>
    <%= a.hidden_field :oauth_secret %>
    <%= a.hidden_field :uid %>
    <%= a.hidden_field :provider %>
  <% end %>

  <%= f.submit "Sign up" %>

<% end %>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>

<% if current_user && @user != current_user %>
  <% friendship = current_user.following?(@user)%>
  <% if friendship %>
    You are following this <%= @user.username %>
    <%= button_to "Unfollow", following_path(friendship), {:method => :delete} %>
  <% else %>
    <%= form_for Friendship.new, :url => user_following_index_path(current_user.username) do |f| %>
      <%= f.hidden_field :friend_id, :value => @user.id %>
      <%= f.submit "Follow" %>
    <% end %>
  <% end %>

<% end %>

<h2>...has been watching:</h2>

<% @user.recent_intentions.each do |intention| %>

  <p>
    <%= link_to intention.broadcast.title, intention.broadcast %>
    <%= intention.broadcast.start.to_s(:long) %>, <%= intention.broadcast.channel.name %>
    <%= (tag("br") + intention.comment).html_safe unless intention.comment.blank? %>
  </p>
<% end %>