config/routes.rb
Appointment::Application.routes.draw do


  get "pages/about"

  resources :channels
  resources :broadcasts
  resource :today, :controller => :today, :only => :show


  resources :users, :only => [:show], :shallow => true do
    resources :following, :only => [:index, :create, :destroy], :controller => :followings
  end
#  resources :followings, :only => [:create, :destroy]
  resources :intentions, :only => [:new, :create, :destroy, :watchers]
  resource :settings, :only => [:show]

  #resources :on, :constraints => {:id => /[0-9][0-9][0-9][0-9]\/[0-9][0-9]\/[0-9][0-9]/}, :as => :day, :controller => :days, :only => :show

  match ':year/:month/:day', :to => 'days#show', :year => /[0-9][0-9][0-9][0-9]/, :month => /[0-9][0-9]/, :day => /[0-9][0-9]/

  match 'logout', :to => 'sessions#destroy'
  match 'watchers', :to => 'intentions#watchers'
  match 'processing', :to => 'pages#processing'
  match '/auth/:provider/callback', :to => 'sessions#create'
  match '/auth/failure', :to => 'pages#index'

  root :to => "homepage#show"

end

app/views/pages/_broadcast.html.erb
<%= content_tag("li", :id => "broadcast#{broadcast.id}", :class => :two) do %>
	<%= content_tag("h3", link_to(prevent_widows(broadcast.title.html_safe).html_safe, broadcast)) %>
	<%= content_tag("span", :class => :channel) do %>
		<%= broadcast.channel.name.html_safe %>
		<%= content_tag("span", broadcast.start.strftime('%H:%M'), :class => :time) %>
		<%= image_tag("film-icon.png", :alt => "Film") if broadcast.is_film %>
	<% end %>
	<%= image_tag(broadcast.image.url(:thumb)) if broadcast.image_file_name %>
	<%= content_tag("span", :class => :description) do %>
		<%= truncate(broadcast.synopsis, :separator => ' ', :length => 80).html_safe %>
	<% end %>
	<%= content_tag("span", hours_and_minutes(broadcast.duration), :class => "prog-length") %>

	<% if signed_in? %>
                <%= render :partial => '/pages/watchers', :locals => { :user => current_user, :broadcast => broadcast } %>
	<% end %>
		
	<% if signed_in? %>
		<% intention = broadcast.intentions.find_by_user_id(current_user.id) %>

		<% unless intention %>
			<%= link_to new_intention_path(:broadcast_id => broadcast.id), :class => "watch-toggle", :remote => true do %><%= content_tag("span", broadcast.intentions.count.to_i.to_s, :class => :count, :title => "Number of people watching this") %><span class="buttontext">Watch</span><% end %>
		<% else %>
			<%= link_to intention_path(intention), :method => :delete, :class => "watch-toggle watching", :remote => true do %><%= content_tag("span", broadcast.intentions.count.to_i.to_s, :class => :count, :title => "Number of people watching this") %><span class="buttontext">Watch</span><% end %>
		<% end %>

	<% else %>
		<%= link_to intentions_path(:broadcast_id => broadcast.id), :method => :post, :class => "watch-toggle" do %><%= content_tag("span", broadcast.intentions.count.to_i.to_s, :class => :count, :title => "Number of people watching this") %><span class="buttontext">Watch</span><% end %>
	<% end %>
		

<% end %>

app/views/pages/_watchers.html.erb
<% watchers =  broadcast.friends(user) %>

<%= content_tag("p", :class => 'viewer-names') do %>
  <% unless watchers.length == 0 %>
    <strong>Watching</strong>
    <% links = watchers.map { |watcher| watcher.username }.slice(0,3).join(", ") %>
    <%= links.html_safe %>
    <% if watchers.length > 3 %>
       and <%= link_to "#{watchers.length-3} more", watchers_path(:broadcast_id => broadcast.id), :class => 'watchers', :remote => true %>
    <% end %>
  <% end %>
<% end %>

app/views/pages/about.html.erb
<h1><%= @title %></h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/index.html.erb
<section>

<% @broadcasts.each_with_index do |broadcasts, index| %>
	<% if broadcasts.size > 0 %>
	<hr/>
	<section class="row programme-list">
	  <h2><%= @broadcast_titles[index] %></h2>
	  <div class="carousel">
	  <% if broadcasts.length > 6 %>
	    <p class="more-programmes">
	    <a class="prev">Previous</a> <a class="next">Next</a>
	    </p>
	  <% end %>
	  <%= content_tag("ol") do %>
	    <% broadcasts.each do |broadcast| %>
	      <%= render :partial => "broadcast", :locals => {:broadcast => broadcast} %>
	    <% end %>
	  <% end %>
	  </div>
	</section>
	<% end %>
<% end %>
</section>

app/views/pages/processing.html.erb
<div id="redirect">
<p>Updating your friends list, please wait ....</p>
<p class="link">If your browser doesn't redirect you please <%= link_to 'click here', processing_path %> to continue.</p>
</div>